### ISSUE TITLE
Mac OSX Build Error/Issue

### ISSUE THREAD

**Issue by skaht** [spesmilo/obelisk#14]
Using Obelisk "git checkout v1.0" source code 

Making check in src
  CXX      message.lo
  CXX      zmq_message.lo
  CXX      client/backend.lo
  CXX      client/interface/interface.lo
  CXX      client/interface/fetch_history.lo
  CXX      client/interface/blockchain.lo
  CXX      client/interface/protocol.lo
  CXX      client/interface/transaction_pool.lo
In file included from ../../obelisk/src/zmq_message.cpp:1:
../../obelisk/src/../include/obelisk/zmq_message.hpp:5:10: fatal error: 'bitcoin/types.hpp' file not found
#include <bitcoin/types.hpp>

Can't seem to locate "bitcoin/types.hpp" file using the "find" command to update CPPFLAGS include paths. (Building off of existing BX-related source code packages that compile and function properly.) Any assistance will be greatly appreciated.

FYSA - Discovered earlier this evening a missing Obelisk-zmq "zmq.hpp" file was located at https://github.com/zeromq/cppzmq.git

**Comment by evoskuil** [comment]
You need to get libbitcoin from the ```version1``` branch.

Also, see [libbitcoin-server](https://github.com/libbitcoin/libbitcoin-server) details build instructions in install.sh.

**Comment by skaht** [comment]
Eric,

Greatly appreciate the pointer to set me straight. I’ve learned the following two key points from you.

1) BX has deprecated SX
2) libbitcoin-server has deprecated Obelisk

I’ll try to stay more on topic.

Cheers,

Scott Holben
Atlanta, GA

**Comment by evoskuil** [comment]
No problem. Yes, we've moved all new development to the libbitcoin repo.
