### ISSUE TITLE
looking into using obelisk as a replacement for bitcoind to receive blocks and unconfirmed transactions

### ISSUE THREAD

**Issue by eriksank** [spesmilo/obelisk#15]
I am in a situation where I do not need a complete blockchain database. Can I use obelisk to just get a copy of unconfirmed transactions and confirmed blocks? In other words, can I use it without the need to setup a database?

**Comment by veox** [comment]
`obelisk` has been superceded by `libbitcoin-server` and is basically unmaintained.

For both cases (`libbitcoin` stack versions 1 and 2 respectively), this is "not implemented", but can be easily done for unconfirmed transactions. Not so much for "confirmed blocks" - I mean, who will be doing validation if not the node itself?

If you're talking about a trusted server setup, take a look at [bx](https://github.com/libbitcoin/libbitcoin-explorer). Or, you might want to write a node using `libbitcoin-node`, `libbitcoin-server` and `libbitcoin-explorer` as examples.

**Comment by ecdsa** [comment]
@veox if the repos in spesmilo are not used anymore, maybe they should be replaced by a proper redirection

**Comment by veox** [comment]
It's more like "archived".

**Comment by ecdsa** [comment]
can you elaborate on that? did the libbitcoin project move, or was it forked by a small group?

**Comment by veox** [comment]
Yup, it was moved. Here's the [announcement](https://lists.dyne.org/lurker/message/20150108.011643.86e3bd51.en.html), and the [history leading up to it](https://lists.dyne.org/lurker/search/20380101.000000.00000000@ml:libbitcoin,spesmilo.en.html).
