### ISSUE TITLE
[Linux] Error Building obelisk

### ISSUE THREAD

**Issue by bobberb** [spesmilo/obelisk#4]
[1m[32m==>[m[1m Extracting sources...[m
[1m[34m  ->[m[1m Creating working copy of  git repo...[m
Cloning into 'obelisk'...
done.
[1m[32m==>[m[1m Starting pkgver()...[m
[1m[32m==>[m[1m Updated version: obelisk-git v0.2.18.g37362e1-1[m
[1m[32m==>[m[1m Starting build()...[m
[1m[32m==>[m[1m Building...[m
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
configure.ac:7: installing 'build-aux/ar-lib'
configure.ac:2: installing 'build-aux/compile'
configure.ac:8: installing 'build-aux/config.guess'
configure.ac:8: installing 'build-aux/config.sub'
configure.ac:6: installing 'build-aux/install-sh'
configure.ac:6: installing 'build-aux/missing'
src/Makefile.am: installing 'build-aux/depcomp'
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/sh: /home/josh/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libbitcoin... yes
checking for libzmq... yes
checking for libconfigxx... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/obelisk/Makefile
config.status: creating src/Makefile
config.status: creating libobelisk.pc
config.status: executing depfiles commands
config.status: executing libtool commands
Making all in include/obelisk
make[1]: Entering directory '/tmp/yaourt-tmp-josh/aur-obelisk-git/src/obelisk/include/obelisk'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/tmp/yaourt-tmp-josh/aur-obelisk-git/src/obelisk/include/obelisk'
Making all in src
make[1]: Entering directory '/tmp/yaourt-tmp-josh/aur-obelisk-git/src/obelisk/src'
depbase=`echo message.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"obelisk\" -DPACKAGE_TARNAME=\"obelisk\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"obelisk\ 0.1\" -DPACKAGE_BUGREPORT=\"genjix@riseup.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"obelisk\" -DVERSION=\"0.1\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -I.  -std=c++11 -DLEVELDB_ENABLED  -I./../include -DSYSCONFDIR=\"/etc\" -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -MT message.lo -MD -MP -MF $depbase.Tpo -c -o message.lo message.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DPACKAGE_NAME=\"obelisk\" -DPACKAGE_TARNAME=\"obelisk\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"obelisk 0.1\"" -DPACKAGE_BUGREPORT=\"genjix@riseup.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"obelisk\" -DVERSION=\"0.1\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -I. -std=c++11 -DLEVELDB_ENABLED -I./../include -DSYSCONFDIR=\"/etc\" -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -MT message.lo -MD -MP -MF .deps/message.Tpo -c message.cpp  -fPIC -DPIC -o .libs/message.o
libtool: compile:  g++ -DPACKAGE_NAME=\"obelisk\" -DPACKAGE_TARNAME=\"obelisk\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"obelisk 0.1\"" -DPACKAGE_BUGREPORT=\"genjix@riseup.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"obelisk\" -DVERSION=\"0.1\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -I. -std=c++11 -DLEVELDB_ENABLED -I./../include -DSYSCONFDIR=\"/etc\" -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -MT message.lo -MD -MP -MF .deps/message.Tpo -c message.cpp -o message.o >/dev/null 2>&1
depbase=`echo zmq_message.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"obelisk\" -DPACKAGE_TARNAME=\"obelisk\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"obelisk\ 0.1\" -DPACKAGE_BUGREPORT=\"genjix@riseup.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"obelisk\" -DVERSION=\"0.1\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -I.  -std=c++11 -DLEVELDB_ENABLED  -I./../include -DSYSCONFDIR=\"/etc\" -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -MT zmq_message.lo -MD -MP -MF $depbase.Tpo -c -o zmq_message.lo zmq_message.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DPACKAGE_NAME=\"obelisk\" -DPACKAGE_TARNAME=\"obelisk\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"obelisk 0.1\"" -DPACKAGE_BUGREPORT=\"genjix@riseup.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"obelisk\" -DVERSION=\"0.1\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -I. -std=c++11 -DLEVELDB_ENABLED -I./../include -DSYSCONFDIR=\"/etc\" -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -MT zmq_message.lo -MD -MP -MF .deps/zmq_message.Tpo -c zmq_message.cpp  -fPIC -DPIC -o .libs/zmq_message.o
libtool: compile:  g++ -DPACKAGE_NAME=\"obelisk\" -DPACKAGE_TARNAME=\"obelisk\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"obelisk 0.1\"" -DPACKAGE_BUGREPORT=\"genjix@riseup.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"obelisk\" -DVERSION=\"0.1\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -I. -std=c++11 -DLEVELDB_ENABLED -I./../include -DSYSCONFDIR=\"/etc\" -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -MT zmq_message.lo -MD -MP -MF .deps/zmq_message.Tpo -c zmq_message.cpp -o zmq_message.o >/dev/null 2>&1
depbase=`echo client/backend.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"obelisk\" -DPACKAGE_TARNAME=\"obelisk\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"obelisk\ 0.1\" -DPACKAGE_BUGREPORT=\"genjix@riseup.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"obelisk\" -DVERSION=\"0.1\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -I.  -std=c++11 -DLEVELDB_ENABLED  -I./../include -DSYSCONFDIR=\"/etc\" -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -MT client/backend.lo -MD -MP -MF $depbase.Tpo -c -o client/backend.lo client/backend.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DPACKAGE_NAME=\"obelisk\" -DPACKAGE_TARNAME=\"obelisk\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"obelisk 0.1\"" -DPACKAGE_BUGREPORT=\"genjix@riseup.net\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DPACKAGE=\"obelisk\" -DVERSION=\"0.1\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -I. -std=c++11 -DLEVELDB_ENABLED -I./../include -DSYSCONFDIR=\"/etc\" -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++11 -MT client/backend.lo -MD -MP -MF client/.deps/backend.Tpo -c client/backend.cpp  -fPIC -DPIC -o client/.libs/backend.o
client/backend.cpp: In member function 'void obelisk::backend_cluster::request(const string&, const data_chunk&, obelisk::backend_cluster::response_handler, const worker_uuid&)':
client/backend.cpp:39:13: error: 'class libbitcoin::async_strand' has no member named 'randomly_queue'
     strand_.randomly_queue(insert_request);
             ^
client/backend.cpp: In member function 'void obelisk::backend_cluster::update()':
client/backend.cpp:56:13: error: 'class libbitcoin::async_strand' has no member named 'randomly_queue'
     strand_.randomly_queue(
             ^
client/backend.cpp: In member function 'void obelisk::backend_cluster::append_filter(const string&, obelisk::backend_cluster::response_handler)':
client/backend.cpp:63:13: error: 'class libbitcoin::async_strand' has no member named 'randomly_queue'
     strand_.randomly_queue(
             ^
client/backend.cpp: In member function 'void obelisk::backend_cluster::receive_incoming()':
client/backend.cpp:75:13: error: 'class libbitcoin::async_strand' has no member named 'randomly_queue'
     strand_.randomly_queue(
             ^
Makefile:645: recipe for target 'client/backend.lo' failed
make[1]: *** [client/backend.lo] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-josh/aur-obelisk-git/src/obelisk/src'
Makefile:465: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by evoskuil** [comment]
Closed due to age and obsolescence.
